
// Create a class called ProductController where we have methods to add the products, add to inventory, update, delete and search products
public class ProductController {
    public void addProduct() {// Add a product to the product list
        // Have a message to add a product with name, category, price per unit, if it needs prescription, supplier. Name should be unique, if there is a product with the same name, the system should throw an exception
        // The product ID should be auto-generated by the system. If there is a product with the same ID, the system should throw an exception.
        // If there is a new product, the system should add it to the product list, with the product ID + 1 from the previous product.
        System.out.println("\n--------Add Product--------");
        String productName = Utility.getString("Product name: ");
        String productCategory = Utility.getString("Category: ");
        double productPrice = Utility.getDouble("Price: ");
        Utility.userInput.nextLine();
        String productPrescription = Utility.getString("Needs Prescription (y/n): ");
        // Validate user input that the user will only enter "y" or "n"
        while (!productPrescription.equalsIgnoreCase("y") && !productPrescription.equalsIgnoreCase("n")) {
            System.out.println("Invalid input. Please try again.");
            productPrescription = Utility.getString("Needs Prescription (y/n): ");
            Utility.userInput.nextLine();
        }

        String productManufacturer = Utility.getString("Manufacturer: ");

        // Create a Product object
        Product.addProduct(IdGenerator.generateID("Product"), productName, productCategory, productPrice, productPrescription, productManufacturer, Utility.getCurrentDateTime());
    }

    public void addToInventory() {// Add to inventory
        // Have a message to add the quantity of the product to the inventory
        System.out.println("\n--------Add to Inventory--------");
        // Find item either by name or product ID. If the product is not found, the system should throw an exception.
        System.out.println("Enter product name or product ID: ");
        String productName = Utility.getString("Product name: ");
        // If space or enter is pressed, the system can skip the next line (which means the product name is not entered, and the system should search for the product by ID)
        String productId = Utility.getString("Product ID: ");
        // If a space or enter is pressed, the system can skip the next line (which means the product ID is not entered, and the system should search for the product by name)

        
        // Print input (for debugging)
        System.out.println("Product name: " + productName);
        System.out.println("Product ID: " + productId);
    }

    public void displayInventory() {// Display inventory
        // Have a message to display the inventory
        System.out.printf("\n %95s", "--------Display Inventory-------- \n");
        System.out.println("||---------------------------------------------------------------------------------------------------------------------------------------------------------------||");
        System.out.printf("|| %-10s || %-15s || %-25s || %-10s || %-15s || %-30s || %-20s ||\n", "ID", "Category", "Name", "Price", "Prescription", "Manufacturer", "Date Added");
        System.out.println("||---------------------------------------------------------------------------------------------------------------------------------------------------------------||");

        // Get product data from the <Product> List from Product.java and display it
        for (Product product : Product.productList) {
            System.out.printf("|| %-10s || %-15s || %-25s || %-10.2f || %-15s || %-30s || %-20s ||\n", 
                product.getProductId(),
                product.getProductCategory(), 
                product.getProductName(), 
                product.getProductPrice(), 
                product.getProductPrescription(), 
                product.getProductManufacturer(),
                product.getProductDateAdded());
        }
        System.out.println("||---------------------------------------------------------------------------------------------------------------------------------------------------------------||");
    }
}
